# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "csharp" ]
  pull_request:
    branches: [ "csharp" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      # Specify the solution file to restore packages for
      run: dotnet restore HelloWorld.sln
      
    - name: Build
      # Specify the solution file to build
      run: dotnet build HelloWorld.sln --no-restore
      
    - name: Test
      # Specify the solution file to run tests for
      run: dotnet test HelloWorld.sln --no-build --verbosity normal
