# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "csharp" ]
  pull_request:
    branches: [ "csharp" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      # Specify the solution file to restore packages for
      run: dotnet restore cppsamples.sln
      
    - name: Build
      # Specify the solution file to build
      run: dotnet build cppsamples.sln --no-restore
      
    - name: Test
      # Specify the solution file to run tests for
      run: dotnet test cppsamples.sln --no-build --verbosity normal

    - name: Embold Analyse
      run: | 
        # Step 1: Download and extract BrowserStack CQ Scanner
        curl https://v1.embold.io/nfs/CLI/browserstack-codequality-scanner.tar.gz -o browserstack-codequality-scanner-archive.tar.gz
        tar xvf browserstack-codequality-scanner-archive.tar.gz
        echo "Download and extract BrowserStack CQ Scanner done"
        # Step 2: Download repository configuration file
        curl --silent --location --request GET "http://18.184.13.138:3054/api/v1/repositories/f0d5a3dd2a0f35dbcb4d0a706e06c7fc/scans/config/download" --header "Authorization:Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc2MDY4OTQwNTg5OSwiaWF0IjoxNzYwNjg5NDA1LCJleHAiOjE3NjMyODE0MDV9.Cw1EgA5-pGZaq-bBJ5SaPd5ACuU-HhLsu1FRbhlai-8BK4WZzsL5WSmGqkCdmZaKb5ald8aBjAMVrnHOIbp1dw" -o repository-configuration.json
        echo "Download repository configuration file done"
        # Step 3: Run scan using the 'analyse' command
        ./browserstack-codequality-scanner/bin/embold-scanner analyse -u http://18.184.13.138:3054 -t eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc2MDY4OTQwNTg5OSwiaWF0IjoxNzYwNjg5NDA1LCJleHAiOjE3NjMyODE0MDV9.Cw1EgA5-pGZaq-bBJ5SaPd5ACuU-HhLsu1FRbhlai-8BK4WZzsL5WSmGqkCdmZaKb5ald8aBjAMVrnHOIbp1dw -r 1906730153ccbad493d3312bb712628d -b . -d ./embold-data -c ./repository-configuration.json -l ./embold-log -sh $GITHUB_WORKSPACE/embold-scanner-home -v
